name: Deploy to Azure Web App

on:
  push:
    branches:
      - master  # Trigger deployment on push to the main branch
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest        
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B78514198A784BE8B581732724D8E8AE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0245A07C8BE648BBADD0E77CDAE739EF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9E43738665714DA3ADD14BC357173373 }}

      
      - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'java-cx-app'
        resource-group-name: 'delete'  # Manually specify the resource group name
        slot-name: 'Production'
        package: '*.jar'
        startup-command: 'java -jar /home/site/wwwroot/helloworld.jar'  # Command to start your app with the JAR file
        clean: '/home/site/wwwroot'  # Specify the /home/site/wwwroot directory to be cleaned before deployment
        target-path: '/home/site/wwwroot'  # Target directory where the app will be deployed
